author: Lupus and Ludo0777
database: false
description: Prevent Players from Building
main: us.lupusbukkit.GuestGuard.GuestGuard
name: 'GuestGuard'
startup: postworld
version: '0.3'
commands:
  gg:
    description: Turn protection on or off
permissions:  
  guestguard.build:
    default: op
    description: Allow players to build
  guestguard.command:
    default: op
    description: Allow players to perform /gg on and /gg off