author: Lupus and Ludo0777
database: false
description: Control what guests can do on your server!
main: us.lupusbukkit.GuestGuard.GuestGuard
name: 'GuestGuard'
startup: postworld
version: '0.4'
permissions:  
  guestguard.build:
    default: op
    description: Allow players to build
  guestguard.command:
    default: op
    description: Allow players to perform /gg on and /gg off
  guestguard.chat:
    default: op
    description: Allow players to chat